
export const environment = {
  production: false,
  apibaseurl: 'http://103.154.184.66:8000/masters/',
  apiactionurl: 'http://103.154.184.66:8000/actions/',
  fetchallcountries: 'getCountries', // Replace with your API's base URL
  fetchprice: 'prices', // Replace with the endpoint or route you want to use
  fetchallstate: 'getStates',
  fetchalldistrict: 'getDistricts',
  fetchroletypes: 'getRoleTypes',
  fetchgsttypes: 'getGSTTypes',
  fetchunits: 'getUnits',
  fetchhsn: 'getHSNNames',
  fetchcgtype: 'getCGSTTypes',
  fetchsegment: 'getSegments',
  fetchindustrytype: 'getIndustryTypes',
  fetchbusinesstype: 'getBusinessTypes',
  fetchexecutive: 'getExecutives',
  fetchcustomertype: 'getCustomertypes',
  fetchleadsource: 'getLeadSources',
  fetchitemtype: 'getItemTypes',
  fetchstocktype: 'getStockTypes',
  addcust: 'customer',
  addvend: 'vendor',
  //fetchexecutive:'getExecutives',
  // fetchcustomertype:'getCustomertypes',
  addlead: 'lead',
  addfollowup: 'followup',
  addledger: 'saveLedger',
  addservice: 'saveservices',
  addgst: 'gst',
  addexecutive: 'saveExecutive',
  editlead: 'editlead',
  adddcin: 'dcin',
  adddcout: 'dcout',
  addsales: 'sales',
  addpurchase: 'purchase',
  addquote: 'quotation',
  addupquote: 'saveupquote',
  addcompany: 'saveCompany',
  addroleofexecutive: 'roleofexecutive',
  addaccount: 'accounts',
  addcreateamc: 'createamc',
  additem: 'item',
  addgroup: 'insert_group',
  additemgroup:'saveItemGroup',
  addUnit: 'createunit',
  addHsn: 'insert_hsn',
  addcomapny: 'createcompany',
  fetchallitemgroups: 'getItemGroups',
  fetchallcust: 'get_customers',
  fetchallvend: 'get_vendors',
  fetchallitem: 'get_items',
  fetchallservice: 'getservices',
  fetchallexecuitve: 'saveExecutive',
  fetchallcompany: 'getcompanys',
  fetchallledger: 'ledgers',
  addattribute: 'insert_attribute',
  adduser: 'adduser',
  addpass: 'password',
  addlogin: 'login',
  addbarcode: 'barcode',
  fetchattribute:'get_attributes',
  addsalereturn:'salereturn',
  addpurchasereturn:'purchasereturn',
};




