
export const environment = {
  production: false,
  apibaseurl: 'http://103.154.184.66:8000/masters/',
  apiactionurl: 'http://103.154.184.66:8000/actions/',
  apiacturl: 'http://103.154.184.66:8000/acts/',
  apiloginurl: 'http://103.154.184.66:8000/app1/',
  apideleteacturl: 'http://103.154.184.66:8000/action/',
  fetchallcountries: 'getCountries', // Replace with your API's base URL
  fetchprice: 'prices', // Replace with the endpoint or route you want to use
  fetchallstate: 'getStates',
  fetchalldistrict: 'getDistricts',
  fetchroletypes: 'getRoleTypes',
  fetchgsttypes: 'getGSTTypes',
  fetchunits: 'getUnits',
  fetchhsn: 'getHSNNames',
  fetchcgtype: 'getCGSTTypes',
  fetchsegment: 'getSegments',
  fetchindustrytype: 'getIndustryTypes',
  fetchbusinesstype: 'getBusinessTypes',
  fetchexecutive: 'getExecutives',
  fetchcustomertype: 'getCustomertypes',
  fetchleadsource: 'getLeadSources',
  fetchitemtype: 'getItemTypes',
  fetchstocktype: 'getStockTypes',
  addcust: 'customer',
  addvend: 'vendor',
  addsignup:'get_signup',
  addlogin: 'appin',

  addlead: 'insert_lead',
  addfollowup: 'insert_lead_followup',
  addledger: 'saveLedger',
  addservice: 'saveservices',
  addgst: 'gst',
  addexecutive: 'saveExecutive',
  editlead: 'editlead',
  adddcin: 'insert_dcin',
  adddcout: 'insert_dcout',
  addsales: 'insert_sales',
  addpurchase: 'insert_purchase',
  addquote: 'insert_quotation',
  addhsrpout: 'insert_hsrpout',
  addhsrpin: 'insert_hsrpin',
  addupquote: 'saveupquote',
  addcompany: 'saveCompany',
  addroleofexecutive: 'insert_insert_executive_roles',
  addaccount: 'accounts',
  addcreateamc: 'createamc',
  additem: 'insert_item',
  addgroup: 'insert_group',
  additemgroup:'saveItemGroup',
  addunit: 'insert_units',
  addHsn: 'insert_hsn',
  addcomapny: 'createcompany',
  fetchallitemgroups: 'getItemGroups',
  fetchallcust: 'get_customers',
  fetchallvend: 'get_vendors',
  fetchallitem: 'get_items/1/1',
  fetchallservice: 'getservices',
  fetchallexecuitve: 'saveExecutive',
  fetchallcompany: 'getcompanys',
  fetchallledger: 'ledgers',
  addattribute: 'insert_attribute',
  adduser: 'adduser',
  addpass: 'password',
  addbarcode: 'barcode',
  fetchattribute:'get_attributes',
  addsalesreturn:'insert_sale_return',
  addpurchasereturn:'insert_purchase_return',
  fetchallquote:'get_quotations',
  fetchalldcin:'get_dcin',
  fetchalldcout:'get_dcout',
  fetchallsales:'get_sales',
  fetchallpurchase:'get_purchase',
  fetchallsalesreturn:'get_sale_return',
  fetchallpurchasereturn:'get_purchase_return',
  fetchallItem:'get_all_items',
  fetchallleads:"get_lead_by_company",
  fetchfollowup:'get_lead_followupx',
  getlang:'lang',
  toasttiming:2000,
  addpayment:'insert_payment',
 addrecepit:'insert_receipt',
 addamc:'insert_amc',
fetchamc:'get_amc',
fetchpayment:'get_payment',
fetchrecepit:'get_receipt',
fetchunit:'get_units',
fetchroleofexecutive:'get_insert_executive_roles',
addroleassign:'roleassign',
fetchitemauto:'get_items',
quoteno:'viewinv.php',
deletecust:'dcustomer',
fetchUserOutstanding:'user_outstanding',
fetchVendorOutstanding:'vendor_outstanding',
deleteCustomer:'dcustomer',
deleteVendor:'dvendor',
deleteItem:'ditem',
deleteExecutive:'dexecutive',
deleteLedger:'dlegder',
recepitbill:'get_sales_byid',
paymentbill:'get_payment_byid'
};




