
export const environment = {
  production: false,
  apibaseurl: 'http://103.154.184.66:8000/masters/',
  apiactionurl:'http://103.154.184.66:8000/actions/',
  fetchallcountries:'getCountries', // Replace with your API's base URL
  fetchprice: 'prices', // Replace with the endpoint or route you want to use
  fetchallstate: 'getStates',
  fetchalldistrict: 'getDistricts',
  fetchroletypes: 'getRoleTypes',
  fetchgsttypes: 'getGSTTypes',
  fetchunits: 'getUnits',
  fetchhsn: 'getHSNNames',
  fetchcgtype: 'getCGSTTypes',
  fetchsegment: 'getSegments',
  fetchindustrytype: 'getIndustryTypes',
  fetchbusinesstype: 'getBusinessTypes',
  fetchexecutive: 'getExecutives',
  fetchcustomertype: 'getCustomertypes',
  fetchitemtype:'getItemTypes',
  fetchstocktype:'getStockTypes',
  addallexecutive:'executive',
  addcust: 'customer',
  addvend: 'vendor',
  //fetchexecutive:'getExecutives',
  // fetchcustomertype:'getCustomertypes',
  addlead:'lead',
  addfollowup:'followup',
  addledger:'ledger',
  addservice:'service',
  addgst:'gst',
  
editlead:'editlead',
adddcin:'dcin',
adddcout:'dcout',
addsales:'sales',
addpurchase:'purchase',
addquote:'quotation',
addupquote:'upquote',
addcompany : 'company',
  addroleofexecutive: 'roleofexecutive',
  addaccount: 'accounts',
  addcreateamc: 'createamc',
  additem: 'item',
  addgroup: 'saveItemGroup',
  addUnit: 'createunit',
  addHsn: 'insert_hsn',
  addcomapny:'createcompany',
  fetchallitemgroups:'getItemGroups',
  fetchallcust: 'get_customers',
  fetchallvend:'get_vendors',
  fetchallitem:'get_items',
  fetchallcompany:'saveCompany',
  fetchallservice:'get_service',
  fetchallexecute:'saveExecutive',
  addexecutive:'executive',
};




